agents:
  agent_0: {host: 127.0.0.1}
  agent_1: {host: 127.0.0.2}
  agent_2: {host: 127.0.0.3}
controller: {host: 127.0.0.1}
enable_localdebug: false
enable_mqdebug: false
mqtt: {host: 127.0.0.1, port: 1883, qos: 0}
traffic_storage: {passwd: '', path: '127.0.0.1:7671', type: DB, user: ''}
workmode: AUTO
