controller: {host: 127.0.0.1}
enable_localdebug: True #False
enable_mqdebug: false
mqtt: {host: 127.0.0.1, port: 1883, qos: 0}
inuithy_shell: {history: /var/log/inuithy/inuithy.cache}
genid: {path: /var/log/inuithy/inuithy.genid}
reportdir: {path: /var/log/inuithy/report}
traffic_storage: {passwd: '', path: '127.0.0.1:19713', type: 'DB:MongoDB', user: ''}
#traffic_storage: {passwd: '', path: '127.0.0.1:1737', type: 'DB:Splunk', user: ''}
#traffic_storage: {passwd: '', path: '127.0.0.1:19713', type: 'DB:Cloud', user: ''}
#traffic_storage: {passwd: '', path: '/var/log/inuithy/tid-{}.csv', type: 'File:CSV', user: ''}
#traffic_storage: {passwd: '', path: '/var/log/inuithy/tid-{}.data', type: 'File:Protobuffer', user: ''}
workmode: AUTO
#workmode: MORNITOR
#workmode: MANUAL
