network_config: inuithy/config/network_config.yaml
target_agents: [agent_0, agent_1, agent_2, agent_3,
                agent_4, agent_5, agent_6, agent_7,
                agent_8, agent_9, agent_a, agent_b,
                agent_c, agent_d, agent_e, agent_f,]
target_traffics: [traffic_6]
traffin_delay: 30
traffic_0:
  duration: 5
  nwlayout: network_0
  pkgrate: 0.5
  pkgsize: 1
  recipients: ['1122', '1123', '1124', '1134']
  senders: ['1111', '1112', '1113', '1114']
traffic_1:
  duration: 180
  nwlayout: network_0
  pkgrate: 0.5
  pkgsize: 2
  recipients: ['1122', '1123', '1124', '1134']
  senders: ['1114']
traffic_2:
  duration: 360
  nwlayout: network_1
  pkgrate: 0.2
  pkgsize: 2
  recipients: ['1122']
  senders: ['1123']
traffic_3:
  duration: 360
  nwlayout: network_1
  pkgrate: 0.2
  pkgsize: 2
  recipients: ['*']
  senders: ['1111']
traffic_4:
  duration: 360
  nwlayout: network_2
  pkgrate: 0.2
  pkgsize: 2
  recipients: ['1144']
  senders: ['*']
traffic_5:
  duration: 10
  nwlayout: network_1
  pkgrate: 0.2
  pkgsize: 2
  recipients: ['*', '11a1', '11c1', '1181', '1101', '1141', '1121', '11e1', '11f1', '1131', '1171']
  senders: ['*']
traffic_6:
  duration: 10
  nwlayout: network_1
  pkgrate: 0.2
  pkgsize: 2
  recipients: ['11b1']
  senders: ['11a2']
