network_config: /opt/inuithy/inuithy/config/network_config.yaml
target_agents: [agent_01] #, agent_1, agent_2, agent_3, agent_4, agent_5, agent_6, agent_7,
 # agent_8, agent_9, agent_a, agent_b, agent_c, agent_d, agent_e, agent_f]
target_phases:
- noi: ['*']
  nwlayout: network_3
  traffics: [traffic_7]
#- noi: ['1122', '1112', '1124']
#  nwlayout: network_0
#  traffics: [traffic_2]
#- noi: ['1122', '1112', '1124']
#  nwlayout: network_1
#  traffics: [traffic_3, traffic_0, traffic_2]
#- noi: ['1122', '1112', '1124']
#  nwlayout: network_0
#  traffics: [traffic_2]
#- noi: ['*']
#  nwlayout: network_2
#  traffics: [traffic_0, traffic_1]
traffic_0:
  dests: ['1122', '1123', '1124', '1134']
  duration: 18
  interval: 5
  pkgsize: 1
  srcs: ['1111', '1112', '1113', '1114']
traffic_1:
  dests: ['1122', '1123', '1124', '1134']
  duration: 18
  interval: 5
  pkgsize: 2
  srcs: ['1114']
traffic_2:
  dests: ['1122']
  duration: 360
  interval: 2
  pkgsize: 2
  srcs: ['1123']
traffic_3:
  dests: ['*']
  duration: 360
  interval: 3
  pkgsize: 2
  srcs: ['1111']
traffic_4:
  dests: ['1144']
  duration: 360
  interval: 5
  pkgsize: 2
  srcs: ['*']
traffic_5:
  dests: ['*']
  duration: 10
  interval: 2
  pkgsize: 2
  srcs: ['*']
traffic_6:
  dests: [11b1]
  duration: 10
  interval: 2
  pkgsize: 2
  srcs: [11a2]
traffic_7:
  dests: ['A004', 'A001']
  duration: 120
  interval: 2
  pkgsize: 50
  srcs: ['A002', 'A003']
traffin_delay: 30
